/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/X71GZtOVsL2
 */
import Link from "next/link";

export function BlogKioske() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-orange-100 dark:bg-gray-900">
      <header className="p-5 bg-[#F8EACD] shadow-md">
        <nav className="bg-orange-100 dark:bg-gray-900 fixed w-full z-20 top-0 start-0 shadow-md">
          <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
            <a
              href="/blog"
              className="flex items-center space-x-3 rtl:space-x-reverse"
            >
              <img className="w-40 h-auto" src="img/header.png" alt="" />
            </a>

            <div
              className="items-center justify-between hidden w-full md:flex md:w-auto md:order-1"
              id="navbar-sticky"
            >
              <ul className="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-orange-100 dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                <li>
                  <a
                    href="#"
                    className="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-orange-300 md:p-0 md:dark:hover:text-black-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
                  >
                    Quem Somos?
                  </a>
                </li>

                <li>
                  <a
                    href="#"
                    className="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-orange-300 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
                  >
                    Contate-nos
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header> 
      
      <main className="px-6 py-8 bg-orange-200">
        <article className="prose prose-lg mx-auto">
          <h2 className="text-2xl font-bold mb-4">Welcome to My Blog</h2>
          <p>
            This is a sample blog post. Lorem ipsum I cannot remember the rest of lorem ipsum and don’t have an internet
            connection right now to look it up.
          </p>
          <figure>
            <img
              alt=""
              className="aspect-[3/2] object-cover w-60 h-80"
              src="/img/imagemenu.png"
            />
            <figcaption>Placeholder image</figcaption>
          </figure>
          <p>In today's post, I'll be sharing my thoughts on...</p>
        </article>
        <article className="prose prose-lg mx-auto mt-12">
          <h2 className="text-2xl font-bold mb-4">Another Blog Post</h2>
          <p>
            This is another sample blog post. Lorem ipsum I cannot remember the rest of lorem ipsum and don’t have an
            internet connection right now to look it up.
          </p>
          <figure>
          <img
              alt=""
              className="aspect-[3/2] object-cover w-60 h-80"
              src="/img/imagemenu.png"
            />
            <figcaption>Placeholder image</figcaption>
          </figure>
          <p>In today's post, I'll be sharing my thoughts on...</p>
        </article>
      </main>
      <footer className="flex items-center justify-center py-4 bg-gray-900 text-white">
        <p>© 2024 My Blog</p>
      </footer>
  </div>
    );
}
