/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qT39EQwaWXD
 */
import Link from "next/link";
import { Button } from "@/components/ui/button";

export function HomeCourseWave() {
  return (
    <div className="bg-orange-100 w-full h-full flex">
      <header className="p-5 bg-orange-100 shadow-md">
        <nav className="bg-orange-100 dark:bg-gray-900 fixed w-full z-20 top-0 start-0 shadow-md">
          <div className="navbar bg-orange-100">
            <div className="flex-1">
              <a className="btn btn-ghost text-xl">
                <img
                  className="justify-between w-40 h-auto"
                  src="/img/header.png"
                />
              </a>
            </div>
            <div className="flex space-x-5">
              <Link href="/externalUser/blog">
                <button className="btn glass">Meus Cursos</button>
              </Link>
              <Link href="/externalUser/blog">
                <button className="btn glass">Jonny me ajuda!</button>
              </Link>
              <Link href="/externalUser/blog">
                <button className="btn glass">Meus Projetos</button>
              </Link>
            </div>
            <div className="flex space-x-5">
              <div className="flex space-x-10">
                <div className="dropdown dropdown-end">
                  <div
                    tabIndex={0}
                    role="button"
                    className="btn btn-ghost btn-circle avatar"
                  >
                    <div className="w-10 rounded-full">
                      <img
                        alt="Tailwind CSS Navbar component"
                        src="https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg"
                      />
                    </div>
                  </div>
                  <ul
                    tabIndex={0}
                    className="mt-3 z-[1] p-2 shadow menu menu-sm dropdown-content bg-base-100 rounded-box w-52"
                  >
                    <li>
                      <a className="justify-between">
                        Profile
                        <span className="badge">New</span>
                      </a>
                    </li>
                    <li>
                      <a>Settings</a>
                    </li>
                    <li>
                      <a>Logout</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </nav>
      </header>

      <section
        className="bg-orange-100 flex-1 p-6"
        style={{ marginTop: "40px" }}
      >
        <div
          className="py-8 px-4 mx-auto  text-center lg:py-16 z-10 relative"
          style={{ marginTop: "40px" }}
        >
          <h2 className="mb-1 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">
            Meus Cursos
          </h2>

          <a className="inline-flex justify-between items-center py-1 px-1 pe-4 mb-5 text-sm text-black-700 bg-orange-100 rounded-full dark:bg-blue-900 dark:text-blue-300 hover:bg-blue-200 dark:hover:bg-blue-800">
            <div className="form-control">
              <input
                type="text"
                placeholder="Search"
                className="input input-bordered w-24 md:w-auto"
              />
            </div>
          </a>
          <button className="btn btn-ghost btn-circle">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-5 w-5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
              />
            </svg>
          </button>
          <h3
            className="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-3xl dark:text-white flex-1 p-6"
            style={{ marginTop: "40px" }}
          >
            <img src="/img/jonny/cool.png" alt="joni" className="w-13 h-11" />
            Olá, !
          </h3>
          <div className="flex space-x-5 flex-wrap justify-center">
            <div>
              <div className="card w-96 glass">
                <figure>
                  <img
                    src="https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_3840,q_auto"
                    alt="car!"
                  />
                </figure>
                <div className="card-body">
                  <h2 className="card-title">Java Script</h2>
                  <p>
                    <progress
                      className="progress progress-accent w-full"
                      value="100"
                      max="100"
                    ></progress>
                  </p>
                  <div className="card-actions justify-end">
                    <button className="btn btn-primary">Concluido!</button>
                  </div>
                </div>
              </div>
            </div>
            <div>
              <div className="card w-96 glass">
                <figure>
                  <img
                    src="https://hermes.dio.me/articles/cover/4cb46a28-34fb-4c72-9588-b5ed52b9470f.jpg"
                    alt="car!"
                  />
                </figure>
                <div className="card-body">
                  <h2 className="card-title">HTML e CSS</h2>
                  <p>
                    <progress
                      className="progress progress-accent w-full"
                      value="10"
                      max="100"
                    ></progress>
                  </p>
                  <div className="card-actions justify-end">
                    <button className="btn btn-primary">Em Progresso!</button>
                  </div>
                </div>
              </div>
            </div>
            <div>
              <div className="card w-96 glass">
                <figure>
                  <img
                    src="https://dkrn4sk0rn31v.cloudfront.net/uploads/2022/05/como-instalar-o-csharp-e-nosso-primeiro-exemplo.png"
                    alt="car!"
                  />
                </figure>
                <div className="card-body">
                  <h2 className="card-title">C#</h2>
                  <p>
                    <progress
                      className="progress progress-accent w-full"
                      value="0"
                      max="100"
                    ></progress>
                  </p>
                  <div className="card-actions justify-end">
                    <button className="btn btn-primary">Bora iniciar!</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
